### ISSUE TITLE
Do you do any filtering on the raw detection boxes from CenterPoint, such as filtering out low score objects and nms? 

### ISSUE THREAD

**Issue by mengnutonomy** [aleksandrkim61/PolarMOT#5]
Or you just feed everything into the network? Thanks.

**Comment by aleksandrkim61** [comment]
Detection boxes are not filtered, false detections are filtered implicitly when they do not get assigned a track and are not reported . I experimented with adding minimum thresholds, but the tradeoff with recall was negative
